### ISSUE TITLE
Bug Libernet 1.5.3

### ISSUE THREAD

**Issue by ivanors** [lutfailham96/openwrt-libernet#1]
Libernet 1.5.3 

Libernet Openwrt 19.07.7 s905x 5.8.18 by reyre
Bug
-Shadowsocks Cloak not connect
-V2Ray Vmess not connect

PULPSTONE REYRE-STB V.18.06 Rev.3.1
Bug
-Openvpn connect Wan IP Tidak berubah Interrnet Bengong

**Comment by lutfailham96** [comment]
> Libernet 1.5.3
> 
> Libernet Openwrt 19.07.7 s905x 5.8.18 by reyre
> Bug
> -Shadowsocks Cloak not connect
> -V2Ray Vmess not connect
> 
> PULPSTONE REYRE-STB V.18.06 Rev.3.1
> Bug
> -Openvpn connect Wan IP Tidak berubah Interrnet Bengong

maaf sebelumnya, project di repository ini tidak ada hubungannya dengan hal tersebut
