### ISSUE TITLE
Uninstall and completely remove Libernet components?

### ISSUE THREAD

**Issue by Falcordog** [lutfailham96/openwrt-libernet#6]
Is there a way that I can remove all related libernet components from the firmware (including the luci menu items - Tunnel/Libernet)?
Thanks!

**Comment by lutfailham96** [comment]
> Is there a way that I can remove all related libernet components from the firmware (including the luci menu items - Tunnel/Libernet)? Thanks!

you can completely remove Libernet by removing binaries & packages from based on installer script reference

https://github.com/lutfailham96/libernet/blob/main/install.sh

**Comment by Falcordog** [comment]
Thanks!
